#!/bin/bash

cd backend/
python3 -m venv env
. ./env/bin/activate
pip3 install -r requirenment.txt
cd project/
python3 manage.py migrate
cd ../../frontend/project/
npm install # --legacy-peer-deps
npm install -r ../requirenment.txt # --legacy-peer-deps
cd ../../

