# Generated by Django 4.0 on 2022-07-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
        ('saves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saves',
            options={'verbose_name': 'Saves', 'verbose_name_plural': 'Saves'},
        ),
        migrations.AlterField(
            model_name='saves',
            name='file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='saves',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
