# Generated by Django 4.0 on 2022-07-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('saves', '0003_saves_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saves',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
