# Generated by Django 4.0 on 2022-07-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name_and_more'),
        ('saves', '0005_alter_saves_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saves',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='username'),
        ),
    ]
